Camera:
  name: 'droid-cam'
  url: ''
  names:
    droid-cam: 
      url: 'http://192.168.1.4:4747/video'
    video:
      url: '/kaggle/input/face-recognition-dataset/Dataset/Video/1.mp4'

Detector:
  name: 'det_500m'
  path: ''
  names:
    yolo11n: '/kaggle/input/gender-face-detection/pytorch/e100-b128/1/best (1).pt'
    det_500m: 'C:\Users\LENOVO-DUCKY\Documents\Python\attend_aita\model\det_500m.onnx'

Recognizer:
  name: 'w600k_mbf'
  names:
    resnet50: ''
    w600k_mbf: 'C:\Users\LENOVO-DUCKY\Documents\Python\attend_aita\model\w600k_mbf.onnx'

NoSQLDatabase:
  name: 'weaviate'
  hostname: '127.0.0.1'
  port: 8080
  persistence_data_path: 'nosql_database'

ObjectDatabase:
  name: 'Faces'
  dir: ''
  max_faces: 3
  names:
    Faces: 'data/faces'

SQLDatabase:
  name: 'sqlite'
  filename: 'sqlite3.db'
  persistence_data_path: 'sql_database'
  sample_data: 'data/raw'