Camera:
  name: 'droid-cam'
  url: ''
  names:
    droid-cam: 
      url: 'http://192.168.170.63:4747/video'
    video:
      url: '/kaggle/input/face-recognition-dataset/Dataset/Video/1.mp4'

Detector:
  name: 'det_500m'
  path: ''
  names:
    yolo11n: '/kaggle/input/gender-face-detection/pytorch/e100-b128/1/best (1).pt'
    det_500m: '/kaggle/working/AiTA-Face-Attendance/buffalo_sc/det_500m.onnx'

Recognizer:
  name: 'mobilefacenet'
  names:
    resnet50: ''
    w600k_mbf: '/kaggle/working/AiTA-Face-Attendance/buffalo_sc/w600k_mbf.onnx'

NoSQLDatabase:
  name: 'weaviate'
  hostname: '127.0.0.1'
  port: 8079
  persistence_data_path: '/kaggle/working/nosql_database'

ObjectDatabase:
  name: 'Faces'
  dir: ''
  max_faces: 3
  names:
    Faces: '/kaggle/input/face-recognition-dataset/Dataset/Faces'

SQLDatabase:
  name: 'sqlite'
  filename: 'sqlite3.db'
  persistence_data_path: '/kaggle/working/sql_database'
  sample_data: 'data/raw'